spring.application.name=climalert

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=climalert0@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

weather.api.url=http://api.weatherapi.com/v1/current.json
weather.api.key=${API_KEY}
weather.location=Buenos Aires
weather.lang=es
weather.alert.emails=admin@clima.com,emergencias@clima.com,meteorologia@clima.com

alert.temp.threshold=35
alert.humidity.threshold=60